version: '3.7'
services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=api
            - POSTGRES_USER=las6731
            - POSTGRES_PASSWORD=password1
